ダークモード対応
Chizuchizu/chizu_blog_hugo pull request #6
Opened 2020-05-26 18:47 UTC by yayoimizuha

大変だったのでダークモード対応だけです。
通常モード:![image](https://user-images.githubusercontent.com/32425706/82938361-a34b7e80-9fcc-11ea-856d-347c681e5318.png)
ダークモード:![image](https://user-images.githubusercontent.com/32425706/82938447-d1c95980-9fcc-11ea-9233-ae50de291f97.png)

2020-05-26 23:55 UTC, chizuchizu requested changes
助かる…… icon.pngを直してくれたらmergeします

2020-05-26 23:55 UTC, Chizuchizu commented on content/blog/test.md
> +img: ["icon.png"]
img/main/icon.png でないと動かないのでは？

2020-05-26 23:55 UTC, Chizuchizu commented on themes/hugo-future-imperfect-slim/layouts/_default/content-list.html
> +  {{ $.Scratch.Set "summary" ((delimit (findRE "<p.*?>(.|\n)*?</p>" .Content 1) "") | truncate (default 140 .Site.Params.summary_length) (default "&hellip;" .Site.Params.text.truncated ) | replaceRE
これがアイキャッチ画像の大きさの設定ですか？

2020-05-26 23:56 UTC, Chizuchizu commented
加えて、アドオンのCSSのrgbは適宜変更しても構わないという理解で合ってる?

2020-05-26 23:58 UTC, merged

2020-05-27 00:04 UTC, yayoimizuha commented on themes/hugo-future-imperfect-slim/layouts/_default/content-list.html
> +  {{ $.Scratch.Set "summary" ((delimit (findRE "<p.*?>(.|\n)*?</p>" .Content 1) "") | truncate (default 140 .Site.Params.summary_length) (default "&hellip;" .Site.Params.text.truncated ) | replaceRE
これは違ったわ。記事一覧で、概要の文字数を設定した。日本語だと500文字もいらないので

2020-05-27 00:04 UTC, yayoimizuha commented
> 加えて、アドオンのCSSのrgbは適宜変更しても構わないという理解で合ってる?

OKです。アクセシビリティとかも考えてやってくださいね。ハロウィンカラーとかみやすいと思うので一応その系統にしてありますが

2020-05-27 00:05 UTC, yayoimizuha commented on content/blog/test.md
> +img: ["icon.png"]
なるほど、変えといて